// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function tezosParameterFormatToString(tezosParameterFormat) {
  if (tezosParameterFormat) {
    return "micheline";
  } else {
    return "michelson";
  }
}

exports.tezosParameterFormatToString = tezosParameterFormatToString;
/* No side effect */
